LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

#
# Servd
#
LOCAL_HDR_FILES := \
	debug.h \
	rtnl.h \
	timer.h

LOCAL_SRC_FILES := \
	rtnl.c \
	timer.c \
	servd.c

SERVAL_INCLUDE_DIR=$(LOCAL_PATH)/../../include

LOCAL_C_INCLUDES += \
	$(SERVAL_INCLUDE_DIR)

LOCAL_LDLIBS :=-lstack
LOCAL_SHARED_LIBRARIES +=libdl libstack

EXTRA_DEFINES:=-DOS_ANDROID -DOS_LINUX -DENABLE_DEBUG -DSERVAL_NATIVE
LOCAL_CFLAGS:=-O2 -g $(EXTRA_DEFINES)
LOCAL_CPPFLAGS +=$(EXTRA_DEFINES)
LOCAL_LDFLAGS +=-L$(LOCAL_PATH)/../libstack/libs/$(TARGET_ARCH_ABI)

LOCAL_PRELINK_MODULE := false
LOCAL_MODULE := servd

# LOCAL_UNSTRIPPED_PATH := $(TARGET_ROOT_OUT_BIN_UNSTRIPPED)

include $(BUILD_EXECUTABLE)
