LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

#
# udp_server
#
LOCAL_HDR_FILES :=

LOCAL_SRC_FILES := \
	udp_server.c

SERVAL_INCLUDE_DIR=$(LOCAL_PATH)/../../include

LOCAL_C_INCLUDES += \
	$(SERVAL_INCLUDE_DIR)

LOCAL_SHARED_LIBRARIES := libdl 

EXTRA_DEFINES:=
DEFINES=-DOS_ANDROID -DOS_LINUX -DSERVAL_NATIVE $(EXTRA_DEFINES)
LOCAL_CFLAGS:=-O2 -g $(DEFINES)
LOCAL_CPPFLAGS +=$(DEFINES) 

LOCAL_PRELINK_MODULE := false
LOCAL_MODULE := udp_server

include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)

#
# udp_client
#
LOCAL_HDR_FILES :=

LOCAL_SRC_FILES := \
	udp_client.c

SERVAL_INCLUDE_DIR=$(LOCAL_PATH)/../../include

LOCAL_C_INCLUDES += \
	$(SERVAL_INCLUDE_DIR)

LOCAL_LDLIBS :=
LOCAL_SHARED_LIBRARIES +=libdl

EXTRA_DEFINES = 
DEFINES=-DOS_ANDROID -DOS_LINUX -DSERVAL_NATIVE $(EXTRA_DEFINES)
LOCAL_CFLAGS:=-O2 -g $(DEFINES)
LOCAL_CPPFLAGS +=$(DEFINES)

LOCAL_PRELINK_MODULE := false
LOCAL_MODULE := udp_client

include $(BUILD_EXECUTABLE)
