/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket */

#ifndef _Included_edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket
#define _Included_edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket
 * Method:    socket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket_socket
  (JNIEnv *, jobject);

/*
 * Class:     edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket
 * Method:    bind
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket_bind
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket
 * Method:    listen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket_listen
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket
 * Method:    accept
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket_accept
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket
 * Method:    connect
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket_connect
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket
 * Method:    send
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket_send
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket
 * Method:    recv
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket_recv
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_princeton_cs_sns_scaffold_ScaffoldDatagramSocket_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
