/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_servalarch_net_ServiceID */

#ifndef _Included_org_servalarch_net_ServiceID
#define _Included_org_servalarch_net_ServiceID
#ifdef __cplusplus
extern "C" {
#endif
#undef org_servalarch_net_ServiceID_SERVICE_ID_MAX_LENGTH
#define org_servalarch_net_ServiceID_SERVICE_ID_MAX_LENGTH 105L
/*
 * Class:     org_servalarch_net_ServiceID
 * Method:    fqdnToService
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_servalarch_net_ServiceID_fqdnToService
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_servalarch_net_ServiceID
 * Method:    serviceToFqdn
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_servalarch_net_ServiceID_serviceToFqdn
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
