/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_servalarch_servalctrl_HostCtrl */

#ifndef _Included_org_servalarch_servalctrl_HostCtrl
#define _Included_org_servalarch_servalctrl_HostCtrl
#ifdef __cplusplus
extern "C" {
#endif
#undef org_servalarch_servalctrl_HostCtrl_HOSTCTRL_LOCAL
#define org_servalarch_servalctrl_HostCtrl_HOSTCTRL_LOCAL 0L
#undef org_servalarch_servalctrl_HostCtrl_HOSTCTRL_REMOTE
#define org_servalarch_servalctrl_HostCtrl_HOSTCTRL_REMOTE 1L
#undef org_servalarch_servalctrl_HostCtrl_RETVAL_OK
#define org_servalarch_servalctrl_HostCtrl_RETVAL_OK 0LL
#undef org_servalarch_servalctrl_HostCtrl_RETVAL_ERROR
#define org_servalarch_servalctrl_HostCtrl_RETVAL_ERROR 1LL
#undef org_servalarch_servalctrl_HostCtrl_RETVAL_NOENTRY
#define org_servalarch_servalctrl_HostCtrl_RETVAL_NOENTRY 2LL
#undef org_servalarch_servalctrl_HostCtrl_RETVAL_MALFORMED
#define org_servalarch_servalctrl_HostCtrl_RETVAL_MALFORMED 3LL
/*
 * Class:     org_servalarch_servalctrl_HostCtrl
 * Method:    nativeInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_servalarch_servalctrl_HostCtrl_nativeInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_servalarch_servalctrl_HostCtrl
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_servalarch_servalctrl_HostCtrl_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     org_servalarch_servalctrl_HostCtrl
 * Method:    migrateFlow
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_servalarch_servalctrl_HostCtrl_migrateFlow
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_servalarch_servalctrl_HostCtrl
 * Method:    migrateInterface
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_servalarch_servalctrl_HostCtrl_migrateInterface
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_servalarch_servalctrl_HostCtrl
 * Method:    addService4
 * Signature: (Lorg/servalarch/net/ServiceID;IIILjava/net/Inet4Address;)I
 */
JNIEXPORT jint JNICALL Java_org_servalarch_servalctrl_HostCtrl_addService4
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject);

/*
 * Class:     org_servalarch_servalctrl_HostCtrl
 * Method:    getService4
 * Signature: (Lorg/servalarch/net/ServiceID;ILjava/net/Inet4Address;)I
 */
JNIEXPORT jint JNICALL Java_org_servalarch_servalctrl_HostCtrl_getService4
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     org_servalarch_servalctrl_HostCtrl
 * Method:    removeService4
 * Signature: (Lorg/servalarch/net/ServiceID;ILjava/net/Inet4Address;)I
 */
JNIEXPORT jint JNICALL Java_org_servalarch_servalctrl_HostCtrl_removeService4
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     org_servalarch_servalctrl_HostCtrl
 * Method:    registerService4
 * Signature: (Lorg/servalarch/net/ServiceID;ILjava/net/Inet4Address;)I
 */
JNIEXPORT jint JNICALL Java_org_servalarch_servalctrl_HostCtrl_registerService4
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     org_servalarch_servalctrl_HostCtrl
 * Method:    unregisterService4
 * Signature: (Lorg/servalarch/net/ServiceID;I)I
 */
JNIEXPORT jint JNICALL Java_org_servalarch_servalctrl_HostCtrl_unregisterService4
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_servalarch_servalctrl_HostCtrl
 * Method:    getXid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_servalarch_servalctrl_HostCtrl_getXid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
